### ISSUE TITLE
Implement DB Mapping, make the app usable for the Apps Team

### ISSUE THREAD

**Issue by LarsTjernstrom** [Starcounter/Blending#69]
# What to do
- [x] Replace Simplified with Local db Model (https://github.com/Starcounter/RebelsLounge/issues/240)
- [x] Refactor so the Authentication works with on branch without Simplified. See any of the apps, People, Search, UserAdmin with the branch without Simplified to see how it's done right now
- [x] Design UI Wireframe complete (https://drive.google.com/drive/u/0/folders/12TeSCAPs0v5unQ-CnckDCqelpTCj5qP4)
- [x] Implement "Underware" (https://github.com/Starcounter/Blending/issues/50)
- [x] Pixel perfect UI design complete (https://github.com/Starcounter/Blending/issues/50)
- [x] "Feature complete" (?)
- [ ] Tests pass
- [ ] Released to Appstore

##### Browsers affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari

**Comment by warpech** [comment]
Thank you @LarsTjernstrom for expressing your expectations towards the next release. For the issues that are already tracked, I have added a reference link.

Some items that I marked as `{?}` require clarification from you:

- what are the problems with Authentication? it works. If you mean that some changes are needed to make it work with mapping, please provide more information
- what do you mean by the point "Feature complete"? Blending app suite has the whole roadmap ahead: https://github.com/Starcounter/CompanyTrack/blob/master/WebPlatform/roadmap-2018q1.md. Do you mean: make sure all features work in the mapping branch?

**Comment by LarsTjernstrom** [comment]
Refactor so the Authentication works with a mapped version of SignIn. If it's allready complete, just check the checkbox
Feature complete is not my input, it's Stefans requirement...but to be complete, you have to have a set of features specified to be able to complete them (and I don't think we have).

**Comment by warpech** [comment]
I will then just assume that it means current features should work on the branch without Simplified.

Please note that any progress in this branch is blocked until https://github.com/Starcounter/RebelsLounge/issues/240 is done.

**Comment by warpech** [comment]
Marked `Implement "Underware" (#50)` as done

**Comment by warpech** [comment]
The remaining tasks are:

- Tests do not pass (https://github.com/Starcounter/Blending/issues/182)
- Import feature does not work (https://github.com/Starcounter/Blending/issues/181)

After the above issues done, we can release a version to the App Warehouse and verify with the apps team that all is done. @malx122 will like to be updated about this, too.

**Comment by PatrykSzwer** [comment]
#182 is closed. About #181 I talked with @miyconst and seems like stardump won't support exporting to already existing database, needed for this part of Blending to work. I'll let you do the decision about what to do with this issue @warpech and @LarsTjernstrom but I think that Blending is basically ready to be released to app warehouse.

**Comment by LarsTjernstrom** [comment]
Concerning
#181
Can’t you make a flatfile, export/import?
So we can complete the mapped version of the Blending Manager?

**Comment by PatrykSzwer** [comment]
> Can’t you make a flatfile, export/import?

I'm not sure what do you mean. I think the only thing that we could do right now is to remove `--skip-schema` from the implementation in BlendingEditor and add comment that importing is possible only for fresh databases.

**Comment by miyconst** [comment]
I think, Lars meant plain text/JSON/XML import/export, without StarDump.

**Comment by PatrykSzwer** [comment]
But will this fix the issue with being unable to import entities to already filled database? Is this more stardump issue or starcounter issue?

**Comment by LarsTjernstrom** [comment]
If you write code in the Blending App itself to export and import the configurations, you can decide what should happen or not.
If the database allready has e.g. a composition for some page, it could be updated. If it’s new it will be added. 

In a production environment you don’t want to turn of a system to get the configuration of the layout in place, that’s one more reason why the Blending App should take care of it’s own import/export.

**Comment by miyconst** [comment]
>But will this fix the issue with being unable to import entities to already filled database? Is this more stardump issue or starcounter issue?

@PatrykSzwer this issue is not StarDump and not Starcounter. It's issue of the Blending App. There is no need to preserve object numbers when importing/exporting data in this particular case, and this is just a feature of the Blending App itself. As @LarsTjernstrom says, it has to be solved on the App level.

**Comment by PatrykSzwer** [comment]
Well, I would argue how much It's an issue of Blending app since blending app is just using API from stardump, there is no any external implementation. 
So I assume the way to go is to export entities from the database with all needed columns except those generated ones, like key/objectNo etc. by using some SQLite library and then importing it the same way (or creating new objects based on data from imported file?) and it should work? Is that somewhere already done or I'll be a precursor of import/export feature in mapping?

**Comment by warpech** [comment]
I have marked "Feature complete" as done because current `master` is merged to `mapping`.

**Comment by warpech** [comment]
The tests for the `mapping` branch pass, but we are not executing them yet with actual mapping turned on. Issue to track this: https://github.com/Starcounter/AdminTrack/issues/552

We will not release the mapped version to the app store, because the installation of apps through the app store does not work yet.

Closing as done.
